id: A4E69E683
title: 'Chapter I: NidÄna'
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:20:33.335289
  last_modified_at: 2022-03-01 21:20:33.335297
