id: A4E69E683
title: 'Chapter II: Praṇidhānacaryā'
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:20:33.337419
  last_modified_at: 2022-03-01 21:20:33.337422
